# Configuration file for the thymio n

# Configuration for the world
world:
  width: 300
  height: 180

# Configuration for the thymio
thymio:
 size:
   width: 1
   length: 1
# Configuration for the webcam
webcam:
  device_id: 3
  matrix:
    - [1484.14935, 0         , 964.220337]
    - [0         , 1490.50225, 539.531044]
    - [0         , 0         , 1         ]
  distortion: [0.154056967, -1.04865202, -0.000689137957, -0.00132248869e-03, 1.48905183]
  resolution: [1920, 1080]
