# Configuration file for the thymio

time_step: 0.1 # s

# Configuration for the controller
controller:
  # The angle tolerance in degrees
  angle_tolerance: 5
  # The distance tolerance in mm
  distance_tolerance: 20
  # The rotation speed scale
  scale_rotation_speed: 50
  # Maximum rotation speed
  max_rotation_speed: 20
  # The translation speed scale
  scale_translation_speed: 0.004
  # Minmimum translation speed
  min_translation_speed: 20
  # Maximum translation speed
  max_translation_speed: 300
  # thymio speed to mm/s scale
  scale_speed: 0.43478260869565216
  # Threshold for kidnapping in mm
  kidnap: 20
  # max iter before avoid obstacles
  obstacles_max_iter: 5
  # base obstacles avoidance speed
  obstacles_speed: 100
  # scale factor for proximity sensors
  scale_sensor: 200
  # weights for obstacle avoidance
  weight_left: [6, 9, -10, -9, -6]
  weight_right: [-6, -9, -10, 9, 6]

   
# Configuration for the world
world:
  width: 500 #mm
  height: 270 #mm
  obstacle_min_area: 300 #mm² 
  aruco_size: 25 #mm

# Configuration for the thymio
thymio:
  size:
    width: 120 #mm
    length: 120 #mm
  margin: 20 #mm
# Configuration for the webcam
webcam:
  device_id: 2
  matrix:
    - [1484.14935, 0         , 964.220337]
    - [0         , 1490.50225, 539.531044]
    - [0         , 0         , 1         ]
  distortion: [0.154056967, -1.04865202, -0.000689137957, -0.00132248869e-03, 1.48905183]
  resolution: [1920, 1080]
  padding: 10 #pixels
